function [Total_Cost,Total_Outbreak_Response,Total_Medical,Total_Productivity_loss]=County_Level_Costs(County_Data_Vaccine_Reduction,Unvaccinated_Cases_County,Vaccinated_Cases_County,Uninsured_Unvaccinated_Cases_County,Uninsured_Vaccinated_Cases_County,Public_Unvaccinated_Cases_County,Public_Vaccinated_Cases_County,Total_Contacts,Unvaccinated_Contacts)

[p_H_Unvaccinated,p_H_Vaccinated,duration_hospitalization]=Hospitalization_Probability();
[Productivity_Days_Lost_Under_15_Case,Productivity_Days_Lost_15_plus_Case,Productivity_Days_Lost_Under_15_Contact,Productivity_Days_Lost_15_plus_Contact,Cost_per_Contact,Cost_per_Vaccine_dose_Private,Cost_per_Vaccine_dose_VFC,Cost_per_Non_Hospitalization,Tests_per_Contact,Cost_per_Test]=Measles_Outbreak_Cost();

[Cost_Case_Medical_Uninsured]= Compute_Direct_Medical_Costs_County('Uninsured',County_Data_Vaccine_Reduction,Uninsured_Unvaccinated_Cases_County,Uninsured_Vaccinated_Cases_County,p_H_Unvaccinated,p_H_Vaccinated,duration_hospitalization,Cost_per_Non_Hospitalization);
[Cost_Case_Medical_Public]= Compute_Direct_Medical_Costs_County('Public',County_Data_Vaccine_Reduction,Public_Unvaccinated_Cases_County,Public_Vaccinated_Cases_County,p_H_Unvaccinated,p_H_Vaccinated,duration_hospitalization,Cost_per_Non_Hospitalization);
[Cost_Case_Medical_Private]= Compute_Direct_Medical_Costs_County('Private',County_Data_Vaccine_Reduction,Unvaccinated_Cases_County-Uninsured_Unvaccinated_Cases_County-Public_Unvaccinated_Cases_County,Vaccinated_Cases_County-Uninsured_Vaccinated_Cases_County-Public_Vaccinated_Cases_County,p_H_Unvaccinated,p_H_Vaccinated,duration_hospitalization,Cost_per_Non_Hospitalization);

[Total_Productivity_loss_Cases,Total_Productivity_loss_Contacts]=Compute_Productivity_Losses_County(County_Data_Vaccine_Reduction,Unvaccinated_Cases_County,Vaccinated_Cases_County,Unvaccinated_Contacts,Productivity_Days_Lost_Under_15_Case,Productivity_Days_Lost_15_plus_Case,Productivity_Days_Lost_Under_15_Contact,Productivity_Days_Lost_15_plus_Contact);


% https://pmc.ncbi.nlm.nih.gov/articles/PMC11309373/#:~:text=In%202023%2C%20approximately%2054%25%20of,)%20born%20during%201994%E2%80%932023.
% 54 % elgible for VFC
Cost_Vac_Age=[(0.54.*Cost_per_Vaccine_dose_VFC+(1-0.54).*Cost_per_Vaccine_dose_Private).*ones(1,4) Cost_per_Vaccine_dose_Private.*ones(1,14)];

Cost_Vaccination_Contacts=zeros(size(Unvaccinated_Cases_County,1),size(Unvaccinated_Cases_County,3));


for ww=1:length(County_Data_Vaccine_Reduction.GEOID)
    Cost_Vaccination_Contacts(ww,:)=Cost_Vac_Age*squeeze(Unvaccinated_Contacts(ww,:,:));
end

Total_Medical=Cost_Case_Medical_Uninsured+Cost_Case_Medical_Public+Cost_Case_Medical_Private;
Testing_Cost=Tests_per_Contact.*Cost_per_Test.*squeeze(sum(Total_Contacts,2));
Contact_Tracing_Costs=Cost_per_Contact.*squeeze(sum(Total_Contacts,2));

Total_Productivity_loss=Total_Productivity_loss_Cases+Total_Productivity_loss_Contacts;
Total_Outbreak_Response=Contact_Tracing_Costs+Testing_Cost+Cost_Vaccination_Contacts;

Total_Cost=Contact_Tracing_Costs+Total_Medical+Testing_Cost+Cost_Vaccination_Contacts+Total_Productivity_loss_Cases+Total_Productivity_loss_Contacts;

end