function Monte_Carlo_Runs(National_Annual_Reduction,NS,Scenario_Plot,Year_Reduced)

[Total_Cases_County,Unvaccinated_Cases_County_Baseline,Vaccinated_Cases_County_Baseline,Uninsured_Unvaccinated_Cases_County,Uninsured_Vaccinated_Cases_County,Public_Unvaccinated_Cases_County,Public_Vaccinated_Cases_County,Total_Contacts_Baseline,Unvaccinated_Contacts_Baseline,Imported_Case]=Monte_Carlo_Incidence(National_Annual_Reduction,NS,Scenario_Plot,Year_Reduced);

save(['Monte_Carlo_Run_' Scenario_Plot '_National_Reduction=' num2str(100*National_Annual_Reduction) '_Year=' num2str(Year_Reduced) '.mat'],'Uninsured_Unvaccinated_Cases_County','Uninsured_Vaccinated_Cases_County','Public_Unvaccinated_Cases_County','Public_Vaccinated_Cases_County','Total_Cases_County','Unvaccinated_Cases_County_Baseline','Vaccinated_Cases_County_Baseline','Total_Contacts_Baseline','Unvaccinated_Contacts_Baseline','Imported_Case');
end